from tkinter import*


container = Tk()

menubar = Menu(container)
container.title("MENU")

filemenu = Menu(menubar, tearoff=0)

filemenu.add_command(label="New file")
filemenu.add_command(label="New Window")
filemenu.add_command(label="New Folder")
filemenu.add_separator()
filemenu.add_command(label="Open File")
filemenu.add_command(label="Open Window")
filemenu.add_command(label="Open Recent")
filemenu.add_separator()
filemenu.add_command(label="Save")
filemenu.add_command(label="Save As")
filemenu.add_command(label="Save All")
filemenu.add_separator()
filemenu.add_command(label="Auto Save")
filemenu.add_command(label="Preferences")
filemenu.add_separator()
filemenu.add_command(label="Revert File")
filemenu.add_command(label="Close Editor")
filemenu.add_command(label="Close Folder")
filemenu.add_command(label="Close Window")
filemenu.add_separator()
filemenu.add_command(label="Exit")
menubar.add_cascade(label="File", menu=filemenu)

Editmenu = Menu(menubar, tearoff=0)

Editmenu.add_command(label="Undo")
Editmenu.add_command(label="Redo")
Editmenu.add_separator()
Editmenu.add_command(label="Cut")
Editmenu.add_command(label="Copy")
Editmenu.add_command(label="Paste")
Editmenu.add_separator()
Editmenu.add_command(label="Find")
Editmenu.add_command(label="Replace")
Editmenu.add_separator()
Editmenu.add_command(label="Find in Files")
Editmenu.add_command(label="Replace in Files")
Editmenu.add_separator()
Editmenu.add_command(label="Toggle Line Comment")
Editmenu.add_command(label="Toggle Block Comment")
Editmenu.add_command(label="Emmet: Expand Abbreviation")
menubar.add_cascade(label="Edit", menu=Editmenu)

Selectionmenu  = Menu(menubar, tearoff=0)

Selectionmenu.add_command(label="Select All")
Selectionmenu.add_command(label="Expand Selection")
Selectionmenu.add_command(label="Shrink Selection")
Selectionmenu.add_separator()
Selectionmenu.add_command(label="Copy Line up")
Selectionmenu.add_command(label="Copy Line Down")
Selectionmenu.add_command(label="Move Line Up")
Selectionmenu.add_command(label="Move Line Down")
Selectionmenu.add_command(label="Duplicate Selection")
Selectionmenu.add_separator()
Selectionmenu.add_command(label="Add Cursor Above")
Selectionmenu.add_command(label="Add Cursor Below")
Selectionmenu.add_command(label="Add Cursor to Line Ends")
Selectionmenu.add_command(label="Add Next Occurence")
Selectionmenu.add_command(label="Add Previous Occurence")
Selectionmenu.add_command(label="Select All Occurences")
Selectionmenu.add_separator()
Selectionmenu.add_command(label="Switch to Ctrl+Click for Multi-Cursor")
Selectionmenu.add_command(label="Column Selection Mode")
menubar.add_cascade(label="Selection", menu=Selectionmenu)

Helpmenu = Menu(menubar, tearoff=0)

Helpmenu.add_command(label="Get Started")
Helpmenu.add_command(label="Show All Commands")
Helpmenu.add_command(label="Documentation")
Helpmenu.add_command(label="Editor Playground")
Helpmenu.add_command(label="Release Notes")
Helpmenu.add_separator()
Helpmenu.add_command(label="Keyboard Shortcuts Reference")
Helpmenu.add_command(label="Video Tutorials")
Helpmenu.add_command(label="Tips and Tricks")
Helpmenu.add_separator()
Helpmenu.add_command(label="Join Us on Twitter")
Helpmenu.add_command(label="Search Feature Requests")
Helpmenu.add_command(label="Report Issue")
Helpmenu.add_separator()
Helpmenu.add_command(label="View License")
Helpmenu.add_command(label="Privacy Statement")
Helpmenu.add_separator()
Helpmenu.add_command(label="Toggle Developer Tools")
Helpmenu.add_command(label="Open Process Explorer")
Helpmenu.add_separator()
Helpmenu.add_command(label="Check for Updates...")
Helpmenu.add_separator()
Helpmenu.add_command(label="About")
menubar.add_cascade(label="Help", menu=Helpmenu)


container.config(menu=menubar)
container.mainloop()